### ISSUE TITLE
There are two "return" statements in the same method without any corresponding "if" statement?

### ISSUE THREAD

**Issue by aquaibm** [sketch-hq/BCCollectionView#2]
In the following method which locates at BCCollectionView.m, there are two return statements in the same method without any corresponding "if" statement. How does this happen? Is this a bug or some kind of special syntax ?

`- (NSIndexSet *) indexesOfItemContentRectsInRect: (NSRect)aRect
{
    NSArray *itemLayouts = [layoutManager itemLayouts];
    NSIndexSet *visibleIndexes = [itemLayouts indexesOfObjectsWithOptions: NSEnumerationConcurrent passingTest: ^BOOL(id itemLayout, NSUInteger idx, BOOL *stop){ return NSIntersectsRect([itemLayout itemRect], aRect); }];
    return visibleIndexes;

```
NSUInteger firstIndex = [layoutManager indexOfItemContentRectAtPoint:NSMakePoint(NSMinX(aRect), NSMinY(aRect))];
NSUInteger lastIndex  = [layoutManager indexOfItemContentRectAtPoint:NSMakePoint(NSMaxX(aRect), NSMaxY(aRect))];

if (firstIndex == NSNotFound)
    firstIndex = 0;

if (lastIndex == NSNotFound)
    lastIndex = [contentArray count]-1;

NSMutableIndexSet *indexes = [NSMutableIndexSet indexSet];
for (NSUInteger i=firstIndex; i<lastIndex+1; i++) {
    if (NSIntersectsRect(aRect, [layoutManager contentRectOfItemAtIndex:i]))
        [indexes addIndex:i];
}
return indexes;
```

}`

**Comment by pieteromvlee** [comment]
Thanks, that is indeed a bug. I think I wrote a shorthand for the code below but forgot to remove the now obsolete stuff. Will update that.
