### ISSUE TITLE
Strange resize issue, causing scrollview background to draw.

### ISSUE THREAD

**Issue by zorn** [sketch-hq/BCCollectionView#4]
I'm trying to implement BCCollectionView in my app and am noticing some strange drawing behavior. It feels like when I'm resizing the content and there is extra room it's not filling the scroll view area with the background color and thus the scroll view background color is being drawn instead (blue in the case of my demo): 

http://media.clickablebliss.com/blog/movies/scrollview_inner_view_resizing.mov

Also curious that the scroll view inner content resizes over time. 

When I added a scroll view to the  example project on aaronbrethorst's fork everything seemed ok.

Been trying to figure this out but am coming up empty. Any ideas?

One other issue I had is how you can sometimes find a sweet spot where the content size causes the scrollbars to appear and the content grid to resize, which causes the scroll bars to disappear, which causes the grid to resize, ad infinitum. Fun times. :)

http://media.clickablebliss.com/blog/movies/dancing_cells.mov

**Comment by zorn** [comment]
So I found my problem and it's not a problem with the view per say. Issue was I was swapping in this view into a NSBox subview. This NSBox was off by 2 pixels. Now BCCollection view uses:

[self visibleRect].size.height

while calculating how to resize. This in turn would decrease the frame by 2, which would fire a notification and force the calculation to be done again, ad infinitum. 

I believe this fixes both of my sample movie bugs so I'll close this ticket.

**Comment by pieteromvlee** [comment]
Indeed it's not filling up the entire scrollview, but that shouldn't be a problem I suppose, right?
Resizing the window will fire viewDidResize and that'll call softReload, which then calls:
- (void)resizeFrameToFitContents

That's the method that's resizing the view and there's no animation going on there. Could it be that for some other reason an animation is triggered here? That'd be my first guess.

As for the other issue, I should probably subtract the scrollbar-width from the view when its not visible to break this loop.
